version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_yaafi
    environment:
      POSTGRES_USER: localhost
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
